// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameStats.proto

package com.lepla.bryan.colorflood2;

public final class GameStatsProto {
  private GameStatsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GameStatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameStats)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * the step count in effect at the beginning of the current game
     * </pre>
     *
     * <code>int32 startingStepCount = 1;</code>
     */
    int getStartingStepCount();

    /**
     * <pre>
     * the current steps left in this game
     * </pre>
     *
     * <code>int32 currentStepCount = 2;</code>
     */
    int getCurrentStepCount();

    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    java.util.List<java.lang.String>
        getUndoBoardStackList();
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    int getUndoBoardStackCount();
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    java.lang.String getUndoBoardStack(int index);
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    com.google.protobuf.ByteString
        getUndoBoardStackBytes(int index);

    /**
     * <pre>
     *the very bottom is the starting board
     * the very top is current board
     * </pre>
     *
     * <code>int32 totalGames = 4;</code>
     */
    int getTotalGames();

    /**
     * <code>int32 totalWins = 5;</code>
     */
    int getTotalWins();
  }
  /**
   * Protobuf type {@code GameStats}
   */
  public  static final class GameStats extends
      com.google.protobuf.GeneratedMessageLite<
          GameStats, GameStats.Builder> implements
      // @@protoc_insertion_point(message_implements:GameStats)
      GameStatsOrBuilder {
    private GameStats() {
      undoBoardStack_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int STARTINGSTEPCOUNT_FIELD_NUMBER = 1;
    private int startingStepCount_;
    /**
     * <pre>
     * the step count in effect at the beginning of the current game
     * </pre>
     *
     * <code>int32 startingStepCount = 1;</code>
     */
    @java.lang.Override
    public int getStartingStepCount() {
      return startingStepCount_;
    }
    /**
     * <pre>
     * the step count in effect at the beginning of the current game
     * </pre>
     *
     * <code>int32 startingStepCount = 1;</code>
     */
    private void setStartingStepCount(int value) {
      
      startingStepCount_ = value;
    }
    /**
     * <pre>
     * the step count in effect at the beginning of the current game
     * </pre>
     *
     * <code>int32 startingStepCount = 1;</code>
     */
    private void clearStartingStepCount() {
      
      startingStepCount_ = 0;
    }

    public static final int CURRENTSTEPCOUNT_FIELD_NUMBER = 2;
    private int currentStepCount_;
    /**
     * <pre>
     * the current steps left in this game
     * </pre>
     *
     * <code>int32 currentStepCount = 2;</code>
     */
    @java.lang.Override
    public int getCurrentStepCount() {
      return currentStepCount_;
    }
    /**
     * <pre>
     * the current steps left in this game
     * </pre>
     *
     * <code>int32 currentStepCount = 2;</code>
     */
    private void setCurrentStepCount(int value) {
      
      currentStepCount_ = value;
    }
    /**
     * <pre>
     * the current steps left in this game
     * </pre>
     *
     * <code>int32 currentStepCount = 2;</code>
     */
    private void clearCurrentStepCount() {
      
      currentStepCount_ = 0;
    }

    public static final int UNDOBOARDSTACK_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> undoBoardStack_;
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getUndoBoardStackList() {
      return undoBoardStack_;
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    @java.lang.Override
    public int getUndoBoardStackCount() {
      return undoBoardStack_.size();
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getUndoBoardStack(int index) {
      return undoBoardStack_.get(index);
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUndoBoardStackBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          undoBoardStack_.get(index));
    }
    private void ensureUndoBoardStackIsMutable() {
      if (!undoBoardStack_.isModifiable()) {
        undoBoardStack_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(undoBoardStack_);
       }
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    private void setUndoBoardStack(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUndoBoardStackIsMutable();
      undoBoardStack_.set(index, value);
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    private void addUndoBoardStack(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUndoBoardStackIsMutable();
      undoBoardStack_.add(value);
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    private void addAllUndoBoardStack(
        java.lang.Iterable<java.lang.String> values) {
      ensureUndoBoardStackIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, undoBoardStack_);
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    private void clearUndoBoardStack() {
      undoBoardStack_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <pre>
     * the collection of board representations to use for undo;
     * </pre>
     *
     * <code>repeated string undoBoardStack = 3;</code>
     */
    private void addUndoBoardStackBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUndoBoardStackIsMutable();
      undoBoardStack_.add(value.toStringUtf8());
    }

    public static final int TOTALGAMES_FIELD_NUMBER = 4;
    private int totalGames_;
    /**
     * <pre>
     *the very bottom is the starting board
     * the very top is current board
     * </pre>
     *
     * <code>int32 totalGames = 4;</code>
     */
    @java.lang.Override
    public int getTotalGames() {
      return totalGames_;
    }
    /**
     * <pre>
     *the very bottom is the starting board
     * the very top is current board
     * </pre>
     *
     * <code>int32 totalGames = 4;</code>
     */
    private void setTotalGames(int value) {
      
      totalGames_ = value;
    }
    /**
     * <pre>
     *the very bottom is the starting board
     * the very top is current board
     * </pre>
     *
     * <code>int32 totalGames = 4;</code>
     */
    private void clearTotalGames() {
      
      totalGames_ = 0;
    }

    public static final int TOTALWINS_FIELD_NUMBER = 5;
    private int totalWins_;
    /**
     * <code>int32 totalWins = 5;</code>
     */
    @java.lang.Override
    public int getTotalWins() {
      return totalWins_;
    }
    /**
     * <code>int32 totalWins = 5;</code>
     */
    private void setTotalWins(int value) {
      
      totalWins_ = value;
    }
    /**
     * <code>int32 totalWins = 5;</code>
     */
    private void clearTotalWins() {
      
      totalWins_ = 0;
    }

    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.lepla.bryan.colorflood2.GameStatsProto.GameStats prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code GameStats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.lepla.bryan.colorflood2.GameStatsProto.GameStats, Builder> implements
        // @@protoc_insertion_point(builder_implements:GameStats)
        com.lepla.bryan.colorflood2.GameStatsProto.GameStatsOrBuilder {
      // Construct using com.lepla.bryan.colorflood2.GameStatsProto.GameStats.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * the step count in effect at the beginning of the current game
       * </pre>
       *
       * <code>int32 startingStepCount = 1;</code>
       */
      @java.lang.Override
      public int getStartingStepCount() {
        return instance.getStartingStepCount();
      }
      /**
       * <pre>
       * the step count in effect at the beginning of the current game
       * </pre>
       *
       * <code>int32 startingStepCount = 1;</code>
       */
      public Builder setStartingStepCount(int value) {
        copyOnWrite();
        instance.setStartingStepCount(value);
        return this;
      }
      /**
       * <pre>
       * the step count in effect at the beginning of the current game
       * </pre>
       *
       * <code>int32 startingStepCount = 1;</code>
       */
      public Builder clearStartingStepCount() {
        copyOnWrite();
        instance.clearStartingStepCount();
        return this;
      }

      /**
       * <pre>
       * the current steps left in this game
       * </pre>
       *
       * <code>int32 currentStepCount = 2;</code>
       */
      @java.lang.Override
      public int getCurrentStepCount() {
        return instance.getCurrentStepCount();
      }
      /**
       * <pre>
       * the current steps left in this game
       * </pre>
       *
       * <code>int32 currentStepCount = 2;</code>
       */
      public Builder setCurrentStepCount(int value) {
        copyOnWrite();
        instance.setCurrentStepCount(value);
        return this;
      }
      /**
       * <pre>
       * the current steps left in this game
       * </pre>
       *
       * <code>int32 currentStepCount = 2;</code>
       */
      public Builder clearCurrentStepCount() {
        copyOnWrite();
        instance.clearCurrentStepCount();
        return this;
      }

      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getUndoBoardStackList() {
        return java.util.Collections.unmodifiableList(
            instance.getUndoBoardStackList());
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      @java.lang.Override
      public int getUndoBoardStackCount() {
        return instance.getUndoBoardStackCount();
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getUndoBoardStack(int index) {
        return instance.getUndoBoardStack(index);
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUndoBoardStackBytes(int index) {
        return instance.getUndoBoardStackBytes(index);
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      public Builder setUndoBoardStack(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setUndoBoardStack(index, value);
        return this;
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      public Builder addUndoBoardStack(
          java.lang.String value) {
        copyOnWrite();
        instance.addUndoBoardStack(value);
        return this;
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      public Builder addAllUndoBoardStack(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllUndoBoardStack(values);
        return this;
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      public Builder clearUndoBoardStack() {
        copyOnWrite();
        instance.clearUndoBoardStack();
        return this;
      }
      /**
       * <pre>
       * the collection of board representations to use for undo;
       * </pre>
       *
       * <code>repeated string undoBoardStack = 3;</code>
       */
      public Builder addUndoBoardStackBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addUndoBoardStackBytes(value);
        return this;
      }

      /**
       * <pre>
       *the very bottom is the starting board
       * the very top is current board
       * </pre>
       *
       * <code>int32 totalGames = 4;</code>
       */
      @java.lang.Override
      public int getTotalGames() {
        return instance.getTotalGames();
      }
      /**
       * <pre>
       *the very bottom is the starting board
       * the very top is current board
       * </pre>
       *
       * <code>int32 totalGames = 4;</code>
       */
      public Builder setTotalGames(int value) {
        copyOnWrite();
        instance.setTotalGames(value);
        return this;
      }
      /**
       * <pre>
       *the very bottom is the starting board
       * the very top is current board
       * </pre>
       *
       * <code>int32 totalGames = 4;</code>
       */
      public Builder clearTotalGames() {
        copyOnWrite();
        instance.clearTotalGames();
        return this;
      }

      /**
       * <code>int32 totalWins = 5;</code>
       */
      @java.lang.Override
      public int getTotalWins() {
        return instance.getTotalWins();
      }
      /**
       * <code>int32 totalWins = 5;</code>
       */
      public Builder setTotalWins(int value) {
        copyOnWrite();
        instance.setTotalWins(value);
        return this;
      }
      /**
       * <code>int32 totalWins = 5;</code>
       */
      public Builder clearTotalWins() {
        copyOnWrite();
        instance.clearTotalWins();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GameStats)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.lepla.bryan.colorflood2.GameStatsProto.GameStats();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "startingStepCount_",
              "currentStepCount_",
              "undoBoardStack_",
              "totalGames_",
              "totalWins_",
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u021a\u0004\u0004\u0005\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.lepla.bryan.colorflood2.GameStatsProto.GameStats> parser = PARSER;
          if (parser == null) {
            synchronized (com.lepla.bryan.colorflood2.GameStatsProto.GameStats.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.lepla.bryan.colorflood2.GameStatsProto.GameStats>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:GameStats)
    private static final com.lepla.bryan.colorflood2.GameStatsProto.GameStats DEFAULT_INSTANCE;
    static {
      GameStats defaultInstance = new GameStats();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        GameStats.class, defaultInstance);
    }

    public static com.lepla.bryan.colorflood2.GameStatsProto.GameStats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GameStats> PARSER;

    public static com.google.protobuf.Parser<GameStats> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
